set(SOURCE_ROOT ${REAL_ENGINE_ROOT}/source)

set(ENGINE_SRC_FILES
    ${SOURCE_ROOT}/source.cmake
    ${SOURCE_ROOT}/core/eastl_allocator.cpp
    ${SOURCE_ROOT}/core/engine.cpp
    ${SOURCE_ROOT}/core/engine.h
    ${SOURCE_ROOT}/core/gui.cpp
    ${SOURCE_ROOT}/core/gui.h
    ${SOURCE_ROOT}/editor/editor.cpp
    ${SOURCE_ROOT}/editor/editor.h
    ${SOURCE_ROOT}/gfx/d3d12/ags.cpp
    ${SOURCE_ROOT}/gfx/d3d12/ags.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_buffer.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_buffer.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_command_list.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_command_list.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_descriptor.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_descriptor.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_device.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_device.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_fence.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_fence.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_header.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_heap.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_heap.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_pipeline_state.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_pipeline_state.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_rt_blas.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_rt_blas.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_rt_tlas.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_rt_tlas.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_shader.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_shader.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_swapchain.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_swapchain.h
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_texture.cpp
    ${SOURCE_ROOT}/gfx/d3d12/d3d12_texture.h
    ${SOURCE_ROOT}/gfx/d3d12/pix_runtime.cpp
    ${SOURCE_ROOT}/gfx/d3d12/pix_runtime.h
    ${SOURCE_ROOT}/gfx/gfx.cpp
    ${SOURCE_ROOT}/gfx/gfx.h
    ${SOURCE_ROOT}/gfx/gfx_buffer.h
    ${SOURCE_ROOT}/gfx/gfx_command_list.h
    ${SOURCE_ROOT}/gfx/gfx_define.h
    ${SOURCE_ROOT}/gfx/gfx_descriptor.h
    ${SOURCE_ROOT}/gfx/gfx_device.h
    ${SOURCE_ROOT}/gfx/gfx_fence.h
    ${SOURCE_ROOT}/gfx/gfx_heap.h
    ${SOURCE_ROOT}/gfx/gfx_pipeline_state.h
    ${SOURCE_ROOT}/gfx/gfx_resource.h
    ${SOURCE_ROOT}/gfx/gfx_rt_blas.h
    ${SOURCE_ROOT}/gfx/gfx_rt_tlas.h
    ${SOURCE_ROOT}/gfx/gfx_shader.h
    ${SOURCE_ROOT}/gfx/gfx_swapchain.h
    ${SOURCE_ROOT}/gfx/gfx_texture.h
    ${SOURCE_ROOT}/physics/physics_body_activation_listener.cpp
    ${SOURCE_ROOT}/physics/physics_body_activation_listener.h
    ${SOURCE_ROOT}/physics/physics_broad_phase_layer.cpp
    ${SOURCE_ROOT}/physics/physics_broad_phase_layer.h
    ${SOURCE_ROOT}/physics/physics_contact_listener.cpp
    ${SOURCE_ROOT}/physics/physics_contact_listener.h
    ${SOURCE_ROOT}/physics/physics_layer.h
    ${SOURCE_ROOT}/physics/physics_layer_filter.cpp
    ${SOURCE_ROOT}/physics/physics_layer_filter.h
    ${SOURCE_ROOT}/physics/physics_system.cpp
    ${SOURCE_ROOT}/physics/physics_system.h
    ${SOURCE_ROOT}/renderer/lighting/clustered_shading.cpp
    ${SOURCE_ROOT}/renderer/lighting/clustered_shading.h
    ${SOURCE_ROOT}/renderer/lighting/gi_denoiser.cpp
    ${SOURCE_ROOT}/renderer/lighting/gi_denoiser.h
    ${SOURCE_ROOT}/renderer/lighting/gi_denoiser_nrd.cpp
    ${SOURCE_ROOT}/renderer/lighting/gi_denoiser_nrd.h
    ${SOURCE_ROOT}/renderer/lighting/gtao.cpp
    ${SOURCE_ROOT}/renderer/lighting/gtao.h
    ${SOURCE_ROOT}/renderer/lighting/hybrid_stochastic_reflection.cpp
    ${SOURCE_ROOT}/renderer/lighting/hybrid_stochastic_reflection.h
    ${SOURCE_ROOT}/renderer/lighting/lighting_processor.cpp
    ${SOURCE_ROOT}/renderer/lighting/lighting_processor.h
    ${SOURCE_ROOT}/renderer/lighting/nrd_integration.cpp
    ${SOURCE_ROOT}/renderer/lighting/nrd_integration.h
    ${SOURCE_ROOT}/renderer/lighting/ray_traced_shadow.cpp
    ${SOURCE_ROOT}/renderer/lighting/ray_traced_shadow.h
    ${SOURCE_ROOT}/renderer/lighting/reflection_denoiser.cpp
    ${SOURCE_ROOT}/renderer/lighting/reflection_denoiser.h
    ${SOURCE_ROOT}/renderer/lighting/restir_gi.cpp
    ${SOURCE_ROOT}/renderer/lighting/restir_gi.h
    ${SOURCE_ROOT}/renderer/lighting/shadow_denoiser.cpp
    ${SOURCE_ROOT}/renderer/lighting/shadow_denoiser.h
    ${SOURCE_ROOT}/renderer/post_processing/automatic_exposure.cpp
    ${SOURCE_ROOT}/renderer/post_processing/automatic_exposure.h
    ${SOURCE_ROOT}/renderer/post_processing/bloom.cpp
    ${SOURCE_ROOT}/renderer/post_processing/bloom.h
    ${SOURCE_ROOT}/renderer/post_processing/cas.cpp
    ${SOURCE_ROOT}/renderer/post_processing/cas.h
    ${SOURCE_ROOT}/renderer/post_processing/dlss.cpp
    ${SOURCE_ROOT}/renderer/post_processing/dlss.h
    ${SOURCE_ROOT}/renderer/post_processing/fsr2.cpp
    ${SOURCE_ROOT}/renderer/post_processing/fsr2.h
    ${SOURCE_ROOT}/renderer/post_processing/fxaa.cpp
    ${SOURCE_ROOT}/renderer/post_processing/fxaa.h
    ${SOURCE_ROOT}/renderer/post_processing/post_processor.cpp
    ${SOURCE_ROOT}/renderer/post_processing/post_processor.h
    ${SOURCE_ROOT}/renderer/post_processing/taa.cpp
    ${SOURCE_ROOT}/renderer/post_processing/taa.h
    ${SOURCE_ROOT}/renderer/post_processing/tonemapper.cpp
    ${SOURCE_ROOT}/renderer/post_processing/tonemapper.h
    ${SOURCE_ROOT}/renderer/post_processing/xess.cpp
    ${SOURCE_ROOT}/renderer/post_processing/xess.h
    ${SOURCE_ROOT}/renderer/resource/constant_buffer.cpp
    ${SOURCE_ROOT}/renderer/resource/constant_buffer.h
    ${SOURCE_ROOT}/renderer/resource/index_buffer.cpp
    ${SOURCE_ROOT}/renderer/resource/index_buffer.h
    ${SOURCE_ROOT}/renderer/resource/raw_buffer.cpp
    ${SOURCE_ROOT}/renderer/resource/raw_buffer.h
    ${SOURCE_ROOT}/renderer/resource/structured_buffer.cpp
    ${SOURCE_ROOT}/renderer/resource/structured_buffer.h
    ${SOURCE_ROOT}/renderer/resource/texture_2d.cpp
    ${SOURCE_ROOT}/renderer/resource/texture_2d.h
    ${SOURCE_ROOT}/renderer/resource/texture_3d.cpp
    ${SOURCE_ROOT}/renderer/resource/texture_3d.h
    ${SOURCE_ROOT}/renderer/resource/texture_cube.cpp
    ${SOURCE_ROOT}/renderer/resource/texture_cube.h
    ${SOURCE_ROOT}/renderer/resource/typed_buffer.cpp
    ${SOURCE_ROOT}/renderer/resource/typed_buffer.h
    ${SOURCE_ROOT}/renderer/base_pass.cpp
    ${SOURCE_ROOT}/renderer/base_pass.h
    ${SOURCE_ROOT}/renderer/directed_acyclic_graph.cpp
    ${SOURCE_ROOT}/renderer/directed_acyclic_graph.h
    ${SOURCE_ROOT}/renderer/gpu_driven_debug_line.cpp
    ${SOURCE_ROOT}/renderer/gpu_driven_debug_line.h
    ${SOURCE_ROOT}/renderer/gpu_driven_debug_print.cpp
    ${SOURCE_ROOT}/renderer/gpu_driven_debug_print.h
    ${SOURCE_ROOT}/renderer/gpu_driven_stats.cpp
    ${SOURCE_ROOT}/renderer/gpu_driven_stats.h
    ${SOURCE_ROOT}/renderer/gpu_scene.cpp
    ${SOURCE_ROOT}/renderer/gpu_scene.h
    ${SOURCE_ROOT}/renderer/hierarchical_depth_buffer.cpp
    ${SOURCE_ROOT}/renderer/hierarchical_depth_buffer.h
    ${SOURCE_ROOT}/renderer/marschner_hair_lut.cpp
    ${SOURCE_ROOT}/renderer/marschner_hair_lut.h
    ${SOURCE_ROOT}/renderer/path_tracer.cpp
    ${SOURCE_ROOT}/renderer/path_tracer.h
    ${SOURCE_ROOT}/renderer/pipeline_cache.cpp
    ${SOURCE_ROOT}/renderer/pipeline_cache.h
    ${SOURCE_ROOT}/renderer/render_batch.h
    ${SOURCE_ROOT}/renderer/render_graph.cpp
    ${SOURCE_ROOT}/renderer/render_graph.h
    ${SOURCE_ROOT}/renderer/render_graph.inl
    ${SOURCE_ROOT}/renderer/render_graph_builder.h
    ${SOURCE_ROOT}/renderer/render_graph_handle.h
    ${SOURCE_ROOT}/renderer/render_graph_pass.cpp
    ${SOURCE_ROOT}/renderer/render_graph_pass.h
    ${SOURCE_ROOT}/renderer/render_graph_resource.cpp
    ${SOURCE_ROOT}/renderer/render_graph_resource.h
    ${SOURCE_ROOT}/renderer/render_graph_resource_allocator.cpp
    ${SOURCE_ROOT}/renderer/render_graph_resource_allocator.h
    ${SOURCE_ROOT}/renderer/renderer.cpp
    ${SOURCE_ROOT}/renderer/renderer.h
    ${SOURCE_ROOT}/renderer/renderer_frame.cpp
    ${SOURCE_ROOT}/renderer/shader_cache.cpp
    ${SOURCE_ROOT}/renderer/shader_cache.h
    ${SOURCE_ROOT}/renderer/shader_compiler.cpp
    ${SOURCE_ROOT}/renderer/shader_compiler.h
    ${SOURCE_ROOT}/renderer/sky_cubemap.cpp
    ${SOURCE_ROOT}/renderer/sky_cubemap.h
    ${SOURCE_ROOT}/renderer/staging_buffer_allocator.cpp
    ${SOURCE_ROOT}/renderer/staging_buffer_allocator.h
    ${SOURCE_ROOT}/renderer/texture_loader.cpp
    ${SOURCE_ROOT}/renderer/texture_loader.h
    ${SOURCE_ROOT}/utils/assert.h
    ${SOURCE_ROOT}/utils/fmt.h
    ${SOURCE_ROOT}/utils/gui_util.h
    ${SOURCE_ROOT}/utils/linear_allocator.h
    ${SOURCE_ROOT}/utils/log.h
    ${SOURCE_ROOT}/utils/math.h
    ${SOURCE_ROOT}/utils/memory.h
    ${SOURCE_ROOT}/utils/parallel_for.h
    ${SOURCE_ROOT}/utils/profiler.h
    ${SOURCE_ROOT}/utils/string.h
    ${SOURCE_ROOT}/utils/system.h
    ${SOURCE_ROOT}/windows/main.cpp
    ${SOURCE_ROOT}/windows/RealEngine.rc
    ${SOURCE_ROOT}/world/animation.cpp
    ${SOURCE_ROOT}/world/animation.h
    ${SOURCE_ROOT}/world/camera.cpp
    ${SOURCE_ROOT}/world/camera.h
    ${SOURCE_ROOT}/world/directional_light.cpp
    ${SOURCE_ROOT}/world/directional_light.h
    ${SOURCE_ROOT}/world/gltf_loader.cpp
    ${SOURCE_ROOT}/world/gltf_loader.h
    ${SOURCE_ROOT}/world/light.h
    ${SOURCE_ROOT}/world/mesh_material.cpp
    ${SOURCE_ROOT}/world/mesh_material.h
    ${SOURCE_ROOT}/world/resource_cache.cpp
    ${SOURCE_ROOT}/world/resource_cache.h
    ${SOURCE_ROOT}/world/skeletal_mesh.cpp
    ${SOURCE_ROOT}/world/skeletal_mesh.h
    ${SOURCE_ROOT}/world/skeleton.cpp
    ${SOURCE_ROOT}/world/skeleton.h
    ${SOURCE_ROOT}/world/sky_sphere.cpp
    ${SOURCE_ROOT}/world/sky_sphere.h
    ${SOURCE_ROOT}/world/static_mesh.cpp
    ${SOURCE_ROOT}/world/static_mesh.h
    ${SOURCE_ROOT}/world/visible_object.cpp
    ${SOURCE_ROOT}/world/visible_object.h
    ${SOURCE_ROOT}/world/world.cpp
    ${SOURCE_ROOT}/world/world.h
)

source_group(TREE ${SOURCE_ROOT} PREFIX source FILES ${ENGINE_SRC_FILES})